version: "3"

services:
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  scanner:
    image: sonarsource/sonar-scanner-cli
    depends_on:
      - sonarqube
    volumes:
      - .:/usr/src # ton code local monté dans le conteneur
    working_dir: /usr/src
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_TOKEN=${SONAR_TOKEN}
    entrypoint: ["sonar-scanner"]

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
